version: '3.3'

services:
  postgres:
    image: postgres:13
    container_name: dbImage
    environment:
      - POSTGRES_DB=Image
      - POSTGRES_USER=fl0user
      - POSTGRES_PASSWORD=2ZkwpAPm9Cox
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80